"""
pdf_generator.py — Dream Success Quiz PDF
wkhtmltopdf use karta hai proper Hindi Devanagari rendering ke liye
asyncio compatible — loop block nahi karta
"""

import io
import os
import asyncio
import subprocess
import tempfile
from datetime import datetime

try:
    from config import BOT_NAME, BOT_USER, TARGET_TXT
except ImportError:
    BOT_NAME   = "Quiz Bot"
    BOT_USER   = "@quizbot"
    TARGET_TXT = "Target Exams"

LABELS = ["A", "B", "C", "D"]

def _e(text):
    """HTML escape."""
    return str(text).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;")

def _build_html(quiz_title, quiz_day, quiz_date, total_questions, scoring,
                leaderboard, questions, student_answers, student_name):
    """Pure HTML build karo — koi blocking call nahi."""

    # Leaderboard rows
    lb_rows = ""
    for row in leaderboard[:60]:
        lb_rows += (
            f"<tr>"
            f"<td>{_e(row.get('rank',''))}</td>"
            f"<td class='name'>{_e(str(row.get('name',''))[:32])}</td>"
            f"<td class='score'>{_e(row.get('score',''))}</td>"
            f"<td>{_e(row.get('wrong',''))}</td>"
            f"<td>{_e(row.get('acc',''))}%</td>"
            f"<td>{_e(row.get('time',''))}</td>"
            f"</tr>"
        )

    # Questions
    def make_q(idx, q):
        chosen  = -1
        if student_answers:
            chosen = student_answers.get(idx, student_answers.get(str(idx), -1))
        correct = q.get("correct", 0)
        opts    = q.get("options", [])
        qtext   = _e(str(q.get("question",""))[:300])
        opts_html = ""
        for j, opt in enumerate(opts[:4]):
            lbl = f"{LABELS[j]}) {_e(opt)}"
            cls = "opt correct" if j == correct else ("opt wrong" if j == chosen else "opt")
            opts_html += f'<div class="{cls}">{lbl}</div>'
        return (
            f'<div class="qcard">'
            f'<div class="qheader"><span class="qnum">Q{idx+1}</span>'
            f'<span class="qtext">{qtext}</span></div>'
            f'{opts_html}</div>'
        )

    q_html = ""
    for i in range(0, len(questions), 2):
        left  = make_q(i, questions[i])
        right = make_q(i+1, questions[i+1]) if i+1 < len(questions) else ""
        q_html += f'<div class="qrow"><div class="qcol">{left}</div><div class="qcol">{right}</div></div>'

    now    = datetime.now().strftime("%d %b %Y, %I:%M %p")
    footer = f"Generated by {_e(BOT_USER)} &bull; Pro Report Edition &bull; {now}"
    if student_name:
        footer = f"Result for: {_e(student_name)} &bull; " + footer

    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:Arial,sans-serif;font-size:10px;color:#212121;padding:12px;line-height:1.5}}
.htitle{{font-size:15px;font-weight:bold;color:#1565C0;text-align:center;margin-bottom:2px}}
.hsub{{font-size:10px;font-weight:bold;color:#1565C0;text-align:center;margin-bottom:2px}}
.hinfo{{font-size:8px;text-align:center;color:#444;margin-bottom:6px}}
hr.t{{border:none;border-top:2px solid #1565C0;margin-bottom:8px}}
hr.b{{border:none;border-top:1px solid #BDBDBD;margin:8px 0}}
.shdr{{background:#1976D2;color:white;font-weight:bold;font-size:10px;padding:5px 8px;margin-bottom:4px}}
table{{width:100%;border-collapse:collapse;margin-bottom:12px}}
th{{background:#1976D2;color:white;font-size:8px;padding:4px;text-align:center}}
td{{font-size:7.5px;padding:3px 4px;border:0.4px solid #BDBDBD;text-align:center}}
td.name{{text-align:left}}
td.score{{font-weight:bold;color:#1565C0}}
tr:nth-child(even) td{{background:#F5F5F5}}
.qrow{{display:flex;gap:5px;margin-bottom:5px}}
.qcol{{flex:1;min-width:0}}
.qcard{{border:0.5px solid #BDBDBD}}
.qheader{{display:flex;align-items:flex-start;background:#F5F5F5}}
.qnum{{background:#1565C0;color:white;font-weight:bold;font-size:7.5px;padding:4px 5px;min-width:22px;text-align:center;flex-shrink:0}}
.qtext{{font-weight:bold;font-size:7.5px;padding:4px 5px;line-height:1.5}}
.opt{{font-size:7px;padding:2px 6px;border-bottom:0.3px solid #BDBDBD;line-height:1.5}}
.opt.correct{{background:#E8F5E9;color:#2E7D32;font-weight:bold}}
.opt.wrong{{background:#FFEBEE;color:#C62828}}
.footer{{font-size:7px;color:#888;text-align:center;margin-top:6px}}
</style></head><body>
<div class="htitle">{_e(BOT_NAME)} &mdash; {_e(quiz_title)}</div>
<div class="hsub">{_e(BOT_USER)}</div>
<div class="hinfo">{_e(TARGET_TXT)} | {_e(quiz_date)} | {total_questions} Questions | {_e(scoring)}</div>
<hr class="t">
<div class="shdr">LEADERBOARD</div>
<table><thead><tr>
<th>Rank</th><th>Participant</th><th>Score</th><th>Wrong</th><th>Acc%</th><th>Time</th>
</tr></thead><tbody>{lb_rows}</tbody></table>
<div class="shdr">QUESTIONS &amp; ANSWERS</div>
<div style="margin-top:5px">{q_html}</div>
<hr class="b">
<div class="footer">{footer}</div>
</body></html>"""


def generate_result_pdf(
    quiz_title, quiz_day, quiz_date, total_questions, scoring,
    leaderboard, questions, student_answers, student_name=None,
) -> io.BytesIO:
    """
    Synchronous wrapper — bot.py mein directly call hota hai.
    wkhtmltopdf ko subprocess.run se chalata hai (thread-safe).
    """
    html = _build_html(
        quiz_title, quiz_day, quiz_date, total_questions, scoring,
        leaderboard, questions, student_answers, student_name
    )

    html_fd, html_path = tempfile.mkstemp(suffix='.html')
    pdf_path = html_path.replace('.html', '.pdf')

    try:
        with os.fdopen(html_fd, 'w', encoding='utf-8') as f:
            f.write(html)

        result = subprocess.run(
            [
                '/usr/bin/wkhtmltopdf',
                '--encoding', 'utf-8',
                '--disable-javascript',
                '--load-error-handling', 'ignore',
                '--load-media-error-handling', 'ignore',
                '--margin-top', '8', '--margin-bottom', '8',
                '--margin-left', '8', '--margin-right', '8',
                '--page-size', 'A4',
                '--quiet',
                html_path, pdf_path
            ],
            capture_output=True, timeout=60
        )

        if os.path.exists(pdf_path) and os.path.getsize(pdf_path) > 0:
            with open(pdf_path, 'rb') as f:
                buf = io.BytesIO(f.read())
            buf.seek(0)
            return buf
        else:
            raise RuntimeError(f"wkhtmltopdf failed: {result.stderr.decode()[:200]}")

    finally:
        try: os.unlink(html_path)
        except: pass
        try: os.unlink(pdf_path)
        except: pass


async def generate_result_pdf_async(
    quiz_title, quiz_day, quiz_date, total_questions, scoring,
    leaderboard, questions, student_answers, student_name=None,
) -> io.BytesIO:
    """
    Async wrapper — asyncio loop block nahi karta.
    finish_quiz mein is function ko use karo.
    """
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(
        None,
        generate_result_pdf,
        quiz_title, quiz_day, quiz_date, total_questions, scoring,
        leaderboard, questions, student_answers, student_name
    )
