"""
pdf_generator.py — Dream Success Quiz PDF
wkhtmltopdf use karta hai — proper Hindi Devanagari rendering
"""

import io
import os
import subprocess
import tempfile
from datetime import datetime

try:
    from config import BOT_NAME, BOT_USER, TARGET_TXT
except ImportError:
    BOT_NAME   = "Quiz Bot"
    BOT_USER   = "@quizbot"
    TARGET_TXT = "Target Exams"

LABELS = ["A", "B", "C", "D"]

# Poppins font path
_FONT_PATH = "/usr/share/fonts/truetype/google-fonts/Poppins-Regular.ttf"
_FONT_BOLD = "/usr/share/fonts/truetype/google-fonts/Poppins-Bold.ttf"

def _html_escape(text):
    return str(text).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;")

def generate_result_pdf(
    quiz_title      : str,
    quiz_day        : str,
    quiz_date       : str,
    total_questions : int,
    scoring         : str,
    leaderboard     : list,
    questions       : list,
    student_answers : dict,
    student_name    : str = None,
) -> io.BytesIO:

    # ── Leaderboard rows ─────────────────────────────────────────────────────
    lb_rows = ""
    for row in leaderboard[:60]:
        lb_rows += f"""
        <tr>
          <td>{_html_escape(row.get('rank',''))}</td>
          <td>{_html_escape(str(row.get('name',''))[:32])}</td>
          <td class="score">{_html_escape(row.get('score',''))}</td>
          <td>{_html_escape(row.get('wrong',''))}</td>
          <td>{_html_escape(row.get('acc',''))}%</td>
          <td>{_html_escape(row.get('time',''))}</td>
        </tr>"""

    # ── Questions grid ────────────────────────────────────────────────────────
    def make_q(idx, q):
        chosen  = -1
        if student_answers:
            chosen = student_answers.get(idx, student_answers.get(str(idx), -1))
        correct = q.get("correct", 0)
        opts    = q.get("options", [])
        question_text = _html_escape(str(q.get("question",""))[:300])

        opts_html = ""
        for j, opt in enumerate(opts[:4]):
            lbl = f"{LABELS[j]}) {_html_escape(opt)}"
            if j == correct:
                cls = "opt correct"
            elif j == chosen:
                cls = "opt wrong"
            else:
                cls = "opt"
            opts_html += f'<div class="{cls}">{lbl}</div>'

        return f"""
        <div class="qcard">
          <div class="qheader">
            <span class="qnum">Q{idx+1}</span>
            <span class="qtext">{question_text}</span>
          </div>
          {opts_html}
        </div>"""

    questions_html = ""
    for i in range(0, len(questions), 2):
        left  = make_q(i, questions[i])
        right = make_q(i+1, questions[i+1]) if i+1 < len(questions) else "<div></div>"
        questions_html += f'<div class="qrow"><div class="qcol">{left}</div><div class="qcol">{right}</div></div>'

    now    = datetime.now().strftime("%d %b %Y, %I:%M %p")
    footer = f"Generated by {BOT_USER} &bull; Pro Report Edition &bull; {now}"
    if student_name:
        footer = f"Result for: {_html_escape(student_name)} &bull; " + footer

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{
  font-family: 'Poppins', 'Noto Sans Devanagari', Arial, sans-serif;
  font-size: 10px;
  color: #212121;
  padding: 12px;
  line-height: 1.4;
}}
.header-title {{
  font-size: 16px;
  font-weight: bold;
  color: #1565C0;
  text-align: center;
  margin-bottom: 2px;
}}
.header-sub {{
  font-size: 11px;
  font-weight: bold;
  color: #1565C0;
  text-align: center;
  margin-bottom: 3px;
}}
.header-info {{
  font-size: 8.5px;
  text-align: center;
  color: #212121;
  margin-bottom: 6px;
}}
hr.thick {{ border: none; border-top: 2px solid #1565C0; margin-bottom: 8px; }}
hr.thin  {{ border: none; border-top: 1px solid #BDBDBD; margin: 8px 0; }}

.section-header {{
  background: #1976D2;
  color: white;
  font-weight: bold;
  font-size: 10px;
  padding: 6px 8px;
  margin-bottom: 4px;
}}

/* Leaderboard */
table {{ width: 100%; border-collapse: collapse; margin-bottom: 12px; }}
th {{
  background: #1976D2;
  color: white;
  font-weight: bold;
  font-size: 8.5px;
  padding: 4px 4px;
  text-align: center;
}}
td {{
  font-size: 8px;
  padding: 3px 4px;
  border: 0.4px solid #BDBDBD;
  text-align: center;
}}
tr:nth-child(even) td {{ background: #F5F5F5; }}
td.score {{ font-weight: bold; color: #1565C0; font-size: 8.5px; }}
td:nth-child(2) {{ text-align: left; }}

/* Questions */
.qrow {{ display: flex; gap: 6px; margin-bottom: 6px; }}
.qcol {{ flex: 1; min-width: 0; }}
.qcard {{
  border: 0.5px solid #BDBDBD;
  margin-bottom: 0;
  height: 100%;
}}
.qheader {{
  display: flex;
  align-items: flex-start;
  background: #F5F5F5;
}}
.qnum {{
  background: #1565C0;
  color: white;
  font-weight: bold;
  font-size: 8px;
  padding: 4px 5px;
  min-width: 22px;
  text-align: center;
  flex-shrink: 0;
}}
.qtext {{
  font-weight: bold;
  font-size: 7.8px;
  padding: 4px 5px;
  line-height: 1.5;
}}
.opt {{
  font-size: 7.5px;
  padding: 3px 6px;
  border-bottom: 0.3px solid #BDBDBD;
  line-height: 1.5;
}}
.opt.correct {{ background: #E8F5E9; color: #2E7D32; font-weight: bold; }}
.opt.wrong   {{ background: #FFEBEE; color: #C62828; }}

.footer {{
  font-size: 7.5px;
  color: #888;
  text-align: center;
  margin-top: 8px;
}}
</style>
</head>
<body>

<div class="header-title">{_html_escape(BOT_NAME)} &mdash; {_html_escape(quiz_title)}</div>
<div class="header-sub">{_html_escape(BOT_USER)}</div>
<div class="header-info">{_html_escape(TARGET_TXT)} | {_html_escape(quiz_date)} | {total_questions} Questions | {_html_escape(scoring)}</div>
<hr class="thick">

<div class="section-header">LEADERBOARD</div>
<table>
  <thead><tr>
    <th>Rank</th><th>Participant</th><th>Score</th>
    <th>Wrong</th><th>Acc%</th><th>Time</th>
  </tr></thead>
  <tbody>{lb_rows}</tbody>
</table>

<div class="section-header">QUESTIONS &amp; ANSWERS</div>
<div style="margin-top:6px">{questions_html}</div>

<hr class="thin">
<div class="footer">{footer}</div>

</body>
</html>"""

    # Write HTML to temp file
    with tempfile.NamedTemporaryFile(suffix='.html', mode='w',
                                     delete=False, encoding='utf-8') as f:
        f.write(html)
        html_path = f.name

    pdf_path = html_path.replace('.html', '.pdf')

    try:
        subprocess.run([
            'wkhtmltopdf',
            '--encoding', 'utf-8',
            '--disable-javascript',
            '--load-error-handling', 'ignore',
            '--load-media-error-handling', 'ignore',
            '--margin-top', '8',
            '--margin-bottom', '8',
            '--margin-left', '8',
            '--margin-right', '8',
            '--page-size', 'A4',
            html_path, pdf_path
        ], capture_output=True, text=True, timeout=60)

        with open(pdf_path, 'rb') as f:
            buf = io.BytesIO(f.read())
        buf.seek(0)
        return buf

    finally:
        try: os.unlink(html_path)
        except: pass
        try: os.unlink(pdf_path)
        except: pass
